- name: Start Mysql Service
  service:
      name: mysql
      state: started
      enabled: yes

- name: Install the Python MySQLB module
  pip:
      name: PyMySQL

- name: Create Application Database
  mysql_db:
      name: "{{ db_name }}"
      state: present

- name: Create Application DB User
  mysql_user:
      name: "{{ dbuser }}"
      password: "{{ db_user_pwd }}"
      priv: "{{ db_name }}.*:ALL,GRANT"
      host: "%"
      state: present

- name: Copy MySql Configuration
  copy:
      src: files/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
      - restart mysql
