- name: Add PHP Repository into Sources List
  apt_repository:
      repo: ppa:ondrej/php
      state: present

- name: Update System Packages
  apt:
      update_cache: yes
      upgrade: no

- name: Install packages
  apt:
      name: "{{ item }}"
      state: latest
  loop: "{{ packages }}"

- name: Clone swap repository
  git:
      repo: https://github.com/Hackathonners/swap.git
      dest: /srv/swap
      force: yes

- name: Copy env file
  template:
      src: .env
      dest: /srv/swap/.env

- name: Install swap dependencies
  shell: cd /srv/swap && composer require predis/predis && composer install && npm install

- name: Run swap
  shell: cd /srv/swap && nohup php artisan serve --host=0.0.0.0 --port=8080 > app_out.log 2>&1 &
