- name: Add PHP Repository into Sources List
  become: yes
  apt_repository:
      repo: ppa:ondrej/php
      state: present

- name: Update System Packages
  become: yes
  apt:
      update_cache: yes
      upgrade: "no"

- name: Install app packages
  become: yes
  apt:
      name: "{{ item }}"
      state: latest
  loop: "{{ packages }}"

- name: Clone swap repository
  git:
      repo: https://github.com/Hackathonners/swap.git
      dest: /srv/swap
      force: yes

- name: Copy env file
  template:
      src: .env
      dest: /srv/swap/.env

# Could use composer and npm ansible modules...
- name: Install Swap cmoposer
  shell: composer require predis/predis && composer install
  args:
      chdir: /srv/swap

- name: Install Swap npm
  shell: npm install
  args:
      chdir: /srv/swap

- name: Generate key Swap
  shell: php artisan key:generate
  args:
      chdir: /srv/swap

# The killall should be improved to a safer command
- name: Clean previous Swap servers
  shell: killall -9 php7.4 && killall -9 php
  ignore_errors: yes

# a more correct approach to this would be to register the service in systemd
- name: Start Swap server
  shell: nohup php artisan serve --host=0.0.0.0 --port=8080 > app_out.log 2>&1 &
  args:
      chdir: /srv/swap
