# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/ubuntu-20.04"
PUBLIC_KEY = File.read(File.expand_path("~/.ssh/id_rsa.pub")).strip
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.provider "virtualbox" do |v|
	v.memory = "512"
	v.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys
    apt-get update
    apt-get -y upgrade
    apt-get -y autoremove
    apt-get install -y vim
  SHELL

  (1..NODE_COUNT).each do |i|
    config.vm.define "sdbtemplate#{i}" do |subconfig|
      subconfig.vm.hostname = "sdbtemplate#{i}"
      
      subconfig.vm.network "private_network", ip: "10.0.0.#{100 + i}"

      subconfig.vm.provider "virtualbox" do |v|
        v.name = "sdbtemplate#{i}"
      end
    end
  end
end
