# -*- mode: ruby -*-
# vi: set ft=ruby :

PUBLIC_KEY = File.read(File.expand_path("~/.ssh/id_rsa.pub")).strip

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"

    config.vm.provider "virtualbox" do |v|
	    v.memory = "512"
	    v.cpus = 1
    end

    config.vm.provision "shell", inline: <<-SHELL
        # add ssh public key
        echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys

        # update software
        apt-get update && apt-get -y upgrade && apt-get -y autoremove

        # install docker
        apt-get install -y software-properties-common curl
        apt-get install -y openjdk-8-jre-headless
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io

        # install docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    SHELL
  
    config.vm.define "dockervm" do |subconfig|
        subconfig.vm.hostname = "dockervm"
        
        subconfig.vm.network "private_network", ip: "10.0.0.101"

        subconfig.vm.provider "virtualbox" do |v|
            v.name = "dockervm"
        end
    end
end
