# provisioning
common_packages:
    - vim-nox
    - openntpd
    - sudo
common_shell: /bin/bash
common_member_of: sudo
common_services:
    - sshd
    - openntpd
common_username: user
common_password: "{{ lookup('file', 'files/hashed_pwd') }}"
common_local_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
