# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/ubuntu-20.04"
PUBLIC_KEY = File.read(File.expand_path('~/.ssh/id_rsa.pub')).strip
NODE_COUNT = 4

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE

    subconfig.vm.hostname = "master"
      
    subconfig.vm.network "private_network", ip: "10.0.0.101"

    subconfig.vm.provider "virtualbox" do |v|
      v.name = "master"
	  v.memory = "512"
	  v.cpus = 1
    end
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE

      subconfig.vm.hostname = "node#{i}"
      
      subconfig.vm.network "private_network", ip: "10.0.0.#{101 + i}"

      subconfig.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
	    v.memory = "1024"
	    v.cpus = 1
      end
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys
    apt-get update
    apt-get -y upgrade
    apt-get -y autoremove
    apt-get install -y vim
  SHELL
end
