- name: VM configuration
  hosts: all
  become: yes
  roles:
      - common
  tags:
      - provision

- name: DB install and start
  hosts: db
  become: yes
  roles:
      - db
  tags:
      - dbinstall

- name: Swap configure, install and deploy
  hosts: app
  roles:
      - app
  tags:
      - appinstall
